set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN V17 [get_ports {SW_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {SW_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {SW_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {SW_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {SW_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {SW_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {SW_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {SW_in[7]}]
set_property PACKAGE_PIN V2 [get_ports {SW_in[8]}]
set_property PACKAGE_PIN T3 [get_ports {SW_in[9]}]
set_property PACKAGE_PIN T2 [get_ports {SW_in[10]}]
set_property PACKAGE_PIN R3 [get_ports {SW_in[11]}]
set_property PACKAGE_PIN W2 [get_ports {SW_in[12]}]
set_property PACKAGE_PIN U1 [get_ports {SW_in[13]}]
set_property PACKAGE_PIN T1 [get_ports {SW_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {SW_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[15]}]

set_property PACKAGE_PIN W4 [get_ports {con_reg[3]}]
set_property PACKAGE_PIN V4 [get_ports {con_reg[2]}]
set_property PACKAGE_PIN U4 [get_ports {con_reg[1]}]
set_property PACKAGE_PIN U2 [get_ports {con_reg[0]}]
set_property PACKAGE_PIN W7 [get_ports {reg_n[6]}]
set_property PACKAGE_PIN W6 [get_ports {reg_n[5]}]
set_property PACKAGE_PIN U8 [get_ports {reg_n[4]}]
set_property PACKAGE_PIN V8 [get_ports {reg_n[3]}]
set_property PACKAGE_PIN U5 [get_ports {reg_n[2]}]
set_property PACKAGE_PIN V5 [get_ports {reg_n[1]}]
set_property PACKAGE_PIN U7 [get_ports {reg_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {con_reg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {con_reg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {con_reg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {con_reg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_n[6]}]


set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

set_property PACKAGE_PIN W19 [get_ports btn_l]
set_property IOSTANDARD LVCMOS33 [get_ports btn_l]

set_property PACKAGE_PIN T17 [get_ports btn_r]
set_property IOSTANDARD LVCMOS33 [get_ports btn_r]

set_property PACKAGE_PIN T18 [get_ports btn_u]
set_property IOSTANDARD LVCMOS33 [get_ports btn_u]

set_property PACKAGE_PIN U17 [get_ports btn_d]
set_property IOSTANDARD LVCMOS33 [get_ports btn_d]

set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

