set_property PACKAGE_PIN V16 [get_ports {d[0]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {d[0]}]
set_property PACKAGE_PIN W16 [get_ports {d[1]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {d[1]}]
set_property PACKAGE_PIN W17 [get_ports {d[2]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {d[2]}]
set_property PACKAGE_PIN W15 [get_ports {d[3]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {d[3]}]

set_property PACKAGE_PIN E19 [get_ports {q[0]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {q[0]}]
set_property PACKAGE_PIN U19 [get_ports {q[1]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {q[1]}]
